services:
  db:
    image: postgres:15
    container_name: db_user
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user_service:
    build: ./user-service
    container_name: user_service
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql+asyncpg://username:password@db:5432/database"
    ports:
      - "8000:8000"

volumes:
  postgres_data:


